//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackBiblioteca.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosPrestamos
    {
        public int ID { get; set; }
        public int IDLibro { get; set; }
        public int IDEstudiante { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
