//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackBiblioteca.Models.ViewModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibreriaDataBase : DbContext
    {
        public LibreriaDataBase()
            : base("name=LibreriaDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstadosPrestamos> EstadosPrestamos { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
    
        public virtual ObjectResult<ObtenerEstados_Result> ObtenerEstados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerEstados_Result>("ObtenerEstados");
        }
    }
}
